#ifndef _ALTERA_FREQUENCYMETER_H_
#define _ALTERA_FREQUENCYMETER_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'FrequencyMeter' in
 * file 'FrequencyMeter.sopcinfo'.
 */

/*
 * This file contains macros for all modules with masters in the system and
 * all the devices connected to those masters.
 * Macro names have unique prefixes to prevent duplicate names.
 */


#endif /* _ALTERA_FREQUENCYMETER_H_ */
